from jack import Jack

# DON'T FORGET TO INVITE THE BOT TO THE SERVER YOU FCKING RETARD
# ALL YOU NEED TO DO IS GO TO OAUTH2, PICK BOT AND THEN ADMIN, AND GO TO THE LINK
# THIS SHOULD NOT HAVE TAKEN THIS LONG TO FIGURE OUT


jack = Jack()
jack.run()
